version: "3.8"

services:
    api-server-db-demo:
        image: postgres:14-alpine
        container_name: postgrest-db-demo
        ports:
            - "5432:5432"
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 10s
            timeout: 7s
            start_period: 2s
            retries: 3
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgrest_db_demo
        volumes:
            - restful-server-data:/var/lib/postgresql/data
        restart: "no"
        networks:
            - postgrest_demo

volumes:
    restful-server-data:

networks:
    postgrest_demo:

